### ISSUE TITLE
Exception has occurred: TypeError 'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by samiraat** [scikit-multiflow/scikit-multiflow#87] opened 2019-02-15 16:15 UTC
why this error happened in evaluation for some csv file when filestream  ?
hi , when i want to Filestream from a csv file i got this message error ."Exception has occurred: TypeError
'NoneType' object is not subscriptable."
for example for music.csv in datasets folder, i got this message too.
for some datasets it works fine , but for some doesnt. for ex, i generate a datastream and save it to csv file and when i want to filestream it , i got that error message.for others like moving_squares or sea_stream it works.
i want to generate a stream from stream generate and save the stream generator to a csv file and add come columns to that csv file and then Filestream that updated csv file , but i got this error in evaluation. ,first i think it was for float numbers , i cant solve the problem . for some csv file int values it does works .

@jacobmontiel 
---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by jacobmontiel** [comment] 2019-02-16 14:00
Hello @samiraat 

I couldn't replicate the error you mention. Could you provide a MWE with the steps to trigger the error?

This is what I used for the `music` dataset:

``` python
from skmultiflow.data import FileStream

stream = FileStream("src/skmultiflow/data/datasets/music.csv", 0, 6)
stream.prepare_for_use()
```

Notice that the `music` datasets contains the labels from column 0-5.

**Comment by samiraat** [comment] 2019-02-16 16:39
`#>>> # Setting up the stream
generate = HyperplaneGenerator ( random_state = 112, n_features= 8, noise_percentage = 0)                              

generate.prepare_for_use()
#>>> # Retrieving one sample
generate.next_sample()

#>>> # Retrieving 10 samples
x , y = generate.next_sample(5000)

#>>> # Generators will have infinite remaining instances, so it returns -1
generate.n_remaining_samples()

generate.has_more_samples()

df = pd.DataFrame(np.hstack((x,np.array([y]).T)))
array = np.hstack((x,np.array([y]).T))

pd.DataFrame(array).to_csv('/home/samira/Projects/Thesis/src/dataset/file.csv', index = None)

stream = FileStream('/home/samira/Projects/Thesis/src/incremental_decision_tree-CART-Random_Forest_python-master/dataset/file.csv')
####### here i want to add some column to array and then save it ################
array2 = global_workspace(array)### add some column to array
dff = pd.DataFrame(array2)
dff.to_csv(path_or_buf='/home/samira/Projects/Thesis/src/dataset/sam.csv' ,sep= ',',index=False)
##################################################3
# 2. Instantiate the HoeffdingTree classifier
ht = HoeffdingTree()

# 3. Setup the evaluator
evaluator = EvaluatePrequential(show_plot=True,
                                pretrain_size=200,
                                max_samples=5000,
                                metrics=['accuracy']
)
# 4. Run evaluation
evaluator.evaluate(stream=stream, model=ht)`
here  i got this error 
Exception has occurred: TypeError
'NoneType' object is not subscriptable


thank you for your response
if also i dont add column i got this error

**Comment by jacobmontiel** [comment] 2019-02-16 19:15
Thanks @samiraat 

The error is raised by the data type of the class data. For classification, the expected data type is `int`. `FileStream` uses the target column data type to infer if the data corresponds to classification (int) or regression (float).

A straightforward solution is as follows:
```
df = pd.DataFrame(np.hstack((x, np.array([y]).T.astype(int))))  # all columns are set as float
df = df.astype({8:int})   # Cast the last column to int
df.to_csv('file.csv')       # write the file with the correct types for classification
```

Using this new file raises no errors. In summary, use `int` to define classification targets (class).

**Comment by samiraat** [comment] 2019-02-17 08:18
`from skmultiflow.data.hyper_plane_generator import HyperplaneGenerator
from skmultiflow.trees import HoeffdingTree
from skmultiflow.evaluation import EvaluatePrequential
from skmultiflow.data.file_stream import FileStream
import pandas as pd
import numpy as np


#>>> # Setting up the stream
generate = HyperplaneGenerator ( random_state = 112, n_features= 8, noise_percentage = 0)                               #n_drift_features =4,

generate.prepare_for_use()
#>>> # Retrieving one sample
generate.next_sample()

#>>> # Retrieving 10 samples
x , y = generate.next_sample(5000)

#>>> # Generators will have infinite remaining instances, so it returns -1
generate.n_remaining_samples()

generate.has_more_samples()

df = pd.DataFrame(np.hstack((x, np.array([y]).T.astype(int))))  # all columns are set as float
df = df.astype({8:int})   # Cast the last column to int
df.to_csv('/home/samira/Projects/Thesis/src/incremental_decision_tree-CART-Random_Forest_python-master/dataset/file.csv' ,index=False)       # write the file with the correct types for classification


stream = FileStream('/home/samira/Projects/Thesis/src/incremental_decision_tree-CART-Random_Forest_python-master/dataset/file.csv')

# 2. Instantiate the HoeffdingTree classifier
ht = HoeffdingTree()

# 3. Setup the evaluator
evaluator = EvaluatePrequential(show_plot=True,
                                pretrain_size=200,
                                max_samples=5000,
                                metrics=['accuracy']
)
# 4. Run evaluation
evaluator.evaluate(stream=stream, model=ht)`

i write this but still get that error.

**Comment by jacobmontiel** [comment] 2019-02-17 11:05
I tried the code above and it works. Are you sure that the file in being correctly generated/read (`df.to_csv(...)`)?

You can validate the stream before passing it to the evaluator by calling:
```
>>> stream.target_values
>>> [0, 1]
```

If you get `[float]` the data is considered as a regression problem and will raise the error.

**Comment by samiraat** [comment] 2019-02-17 18:26
you know i see in file.csv target show int , but
`array = dff.values
print ("array",array)`
array [[0.344983   0.37854446 0.78476361 ... 0.29006973 0.04500817 0.        ]
 [0.73653322 0.83921149 0.70936161 ... 0.50315448 0.76353033 1.        ]
 [0.72195738 0.21415209 0.76309258 ... 0.23435109 0.54902872 1.        ]
 ...
 [0.94708062 0.60475618 0.98433661 ... 0.51317283 0.03259431 0.        ]
 [0.35267571 0.19393065 0.29854344 ... 0.70772311 0.85151878 0.        ]
 [0.32297207 0.90823828 0.73929099 ... 0.62148848 0.88663669 0.        ]]
but it shows float .
`print("target ", stream.target_values)`
target  None
thanks for your help

**Comment by jacobmontiel** [comment] 2019-02-17 18:57
The  [`values`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html) property in pandas' DataFrames returns a numpy representation of the data. You see all floats because numpy's ndarray does not support mixed data types, on the other hand pandas' dataframes support mixed types. You can use the dataframe's `dtypes` property to confirm the data type of each column.

About the `None` when calling `stream.target_values` my assumption is that you are calling it before `stream.prepare_for_use()`

Here is the code I used:

``` python
from skmultiflow.data import HyperplaneGenerator
from skmultiflow.trees import HoeffdingTree
from skmultiflow.evaluation import EvaluatePrequential
from skmultiflow.data.file_stream import FileStream
import pandas as pd
import numpy as np
generate = HyperplaneGenerator ( random_state = 112, n_features= 8, noise_percentage = 0)
generate.prepare_for_use()
x , y = generate.next_sample(5000)
df = pd.DataFrame(np.hstack((x, np.array([y]).T)))  # all columns are set as float
df = df.astype({8:int})                             # Cast the last column to int
df.to_csv('file.csv', index=False)
stream = FileStream('file.csv')
stream.prepare_for_use()
ht = HoeffdingTree()
evaluator = EvaluatePrequential(show_plot=True,
pretrain_size=200,
max_samples=5000,
metrics=['accuracy']
)
evaluator.evaluate(stream=stream, model=ht)
```

Checking the data types in the data frame used to generate the file:
``` python
df.dtypes
Out[3]: 
0    float64
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
8      int64
dtype: object
```

**Comment by jacobmontiel** [comment] 2019-02-20 10:35
Closing this non-issue thread.

**Closed by jacobmontiel** 2019-02-20 10:35 UTC
Labels: question

**Comment by samiraat** [comment] 2019-02-20 14:27
thanks for ur help, it works.

**Comment by samiraat** [comment] 2019-02-20 14:41
how can i print split nodes for hoeffding tree?

**Comment by jacobmontiel** [comment] 2019-02-20 14:51
Calling the `get_model_description()` method of the trained HoeffdingTree object

**Comment by samiraat** [comment] 2019-02-20 15:31
Leaf = Class 1 | {0: 139.0, 1: 261.0} 
that print like this , what does it mean ?

**Comment by jacobmontiel** [comment] 2019-02-20 18:26
The class of the leaf node and its distribution. If you get a single node it means that the tree has not seen enough data to perform a split. Here is an example of a tree with a split node on the root (attribute 7) and its two leaves:

```
if Attribute 7 <= 0.545663049533489:
  Leaf = Class 0 | {0: 1788.339296113556, 1: 1020.3104876835946}
if Attribute 7 > 0.545663049533489:
  Leaf = Class 1 | {0: 801.660703886444, 1: 1389.6895123164054}
```

And the same tree trained with double the number of sample:
```
if Attribute 7 <= 0.545663049533489:
  if Attribute 2 <= 0.5455084120220284:
    Leaf = Class 0 | {0: 1532.3618909765974, 1: 516.4340734943195}
  if Attribute 2 > 0.5455084120220284:
    Leaf = Class 1 | {0: 817.6381090234028, 1: 839.5659265056805}
if Attribute 7 > 0.545663049533489:
  if Attribute 2 <= 0.45478498341966755:
    Leaf = Class 1 | {0: 618.6610367936137, 1: 695.2720517666057}
  if Attribute 2 > 0.45478498341966755:
    Leaf = Class 1 | {0: 381.3389632063864, 1: 1198.7279482333943}
```

**Comment by samiraat** [comment] 2019-02-20 18:37
you are right.

**Comment by samiraat** [comment] 2019-02-20 19:13
can i just save the attributes select for spilit and their depth?

**Comment by samiraat** [comment] 2019-02-20 19:28
can i do Prequential Cross-Validation Evaluation ?

**Comment by jacobmontiel** [comment] 2019-02-21 17:28
> can i just save the attributes select for spilit and their depth?

Not natively, but you could parse the string.

> can i do Prequential Cross-Validation Evaluation ?

This is not currently supported.

For further questions, please use the user's [group](https://groups.google.com/forum/#!forum/scikit-multiflow-users)

Cheers

**Comment by samiraat** [comment] 2019-02-22 07:05
tnx a lot

**Comment by coursestraining** [comment] 2020-09-07 08:05
If you need a fully details about this issue, Visit [Python - TypeError – NoneType Object not Subscriptable](https://360digitmg.com/python-typeerror-nonetype-object-is-not-subsriptable) it will helps you a lot.
