### ISSUE TITLE
[BUG]ConceptDriftStream generate bug.

### ISSUE THREAD

**Issue by zhanghaooo** [scikit-multiflow/scikit-multiflow#177] opened 2019-12-11 06:53 UTC
Hi, there is a bug in ConceptDriftStream.next_sample() when it use DataStream as stream and drift_stream

![image](https://user-images.githubusercontent.com/35730721/70598435-d1f3b980-1c25-11ea-87fc-b3665d5ab634.png)

this is my code:
```python 
from skmultiflow.data import ConceptDriftStream
from skmultiflow.data import HyperplaneGenerator
from skmultiflow.data import DataStream

stream = HyperplaneGenerator(n_features=2)
stream.prepare_for_use()
X, y = stream.next_sample(100)

stream = ConceptDriftStream(stream=DataStream(X, y, name="stream1"),
                            drift_stream=DataStream(X, y, name="stream2"))

stream.prepare_for_use()
X, y = stream.next_sample(100)
```

**Comment by jacobmontiel** [comment] 2019-12-12 22:45
Thanks for reporting this @zhanghaooo and providing the MWE.

I can confirm the bug. The root cause is in the initialization of the concept drift stream. In this case, the two input streams are not initialized and their metadata is not available.

A temporary workaround is:

```python
from skmultiflow.data import ConceptDriftStream
from skmultiflow.data import HyperplaneGenerator
from skmultiflow.data import DataStream

stream = HyperplaneGenerator(n_features=2)
stream.prepare_for_use()
X, y = stream.next_sample(100)

stream1=DataStream(X, y, name="stream1")
stream2=DataStream(X, y, name="stream2")
stream1.prepare_for_use()
stream2.prepare_for_use()

stream = ConceptDriftStream(stream=stream1,
                            drift_stream=stream2)

stream.prepare_for_use()
X, y = stream.next_sample(100)
```

We will submit a fix on the development branch soon.

**Comment by jacobmontiel** [comment] 2020-02-06 21:39
Addressed in #205 and the fix is in 03651318e8b039a80c5058c09d021f2c750f98b6

**Closed by jacobmontiel** 2020-02-06 21:39 UTC
Labels: bug
