### ISSUE TITLE
Prequential Evaluation - IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by hitz9** [scikit-multiflow/scikit-multiflow#250] opened 2020-05-16 16:43 UTC
Hi, I have a csv file with x and y variables. I want to do a regression and this is my code and my dataset:

***SEE THE COMMENTS*** ERROR UPDATE

![](https://i.gyazo.com/7bf83c4b91d01fdf59daaa93dc5252c1.png)

![](https://i.gyazo.com/e3c90b8470c5827bbc54dc798e82fb02.png)

But... when I run the model I got:

![](https://i.gyazo.com/a33dfa14e61d219bb039f6f0d0d43189.png)

What's happening? Thank you in advance.

**Comment by Askios** [comment] 2020-05-16 17:06
No really sure but I had a similar problem with Classification: target_idx=1 should fix it, indexing starts at 0, not at 1 in Python. You're giving the classifier a target that doesn't exists.

**Comment by hitz9** [comment] 2020-05-16 17:10
> No really sure but I had a similar problem with Classification: target_idx=1 should fix it, indexing starts at 0, not at 1 in Python. You're giving the classifier a target that doesn't exist.

Great! But the error continues

**Comment by smastelini** [comment] 2020-05-16 21:20
Hi @hitz9. I believe your problem happens because you are using a learning model usually applied in multivariate analysis in an univariate regression problem. `HoeffdingTreeRegressor` expects a matrix of input variables describing the target, while it is getting only a scalar. That's why you are getting these index errors. Decision trees work by creating orthogonal splits in the input space, but in your case this space is unidimensional

I advise you to use a simple linear model instead.

**Comment by smastelini** [comment] 2020-05-16 21:21
Thanks @Askios for mentioning the problem with the index of the target. :)

**Comment by jacobmontiel** [comment] 2020-06-02 23:30
Closing this issue because there has been further information from the original author. No action is required.

**Closed by jacobmontiel** 2020-06-02 23:30 UTC
Labels: invalid, question
