### ISSUE TITLE
Error: 'NoneType' on get_data for Half-Space Trees

### ISSUE THREAD

**Issue by Askios** [scikit-multiflow/scikit-multiflow#249] opened 2020-05-16 15:19 UTC
Hello, i'm having the following issue while trying to use the evaluate_prequential with an Half-Space Trees.
my code is the following:

```
# 0. imports
%matplotlib notebook
from skmultiflow.data import FileStream
from skmultiflow.anomaly_detection import HalfSpaceTrees
from skmultiflow.evaluation import EvaluatePrequential

# 1. Create a stream
stream = FileStream("/Users/.../Desktop/datasets/HST/datastream_HST/datastream user1_1.csv",target_idx=5)
%the .csv file is a 10000x6 table with the class identifier in the 6th column as int while the other 5
%columns are the features as float
stream.prepare_for_use()

# 2. Instantiate the Half-Space Tree classifier
hst = HalfSpaceTrees(n_features=5,
                     window_size=400,
                     depth=15,
                     size_limit=40,
                     anomaly_threshold=0.5)

# 3. Setup the evaluator
evaluator = EvaluatePrequential(batch_size=1,
                                n_wait=0,
                                show_plot=False,
                                max_samples=10000,
                                metrics=['precision', 'recall'],
                                output_file='1_1.csv')

# 4. Run evaluation
evaluator.evaluate(stream=stream, model=hst,model_names=['HST'])
```

The output is the following:

Prequential Evaluation
Evaluating 1 target(s).
Pre-training on 200 sample(s).
Evaluating...
unsupported operand type(s) for +=: 'int' and 'NoneType'
Processed samples: 201
Mean performance:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-e22cb4c36dbb> in <module>
     24 
     25 # 4. Run evaluation
---> 26 evaluator.evaluate(stream=stream, model=hst,model_names=['HST'])

~/opt/anaconda3/lib/python3.7/site-packages/skmultiflow/evaluation/evaluate_prequential.py in evaluate(self, stream, model, model_names)
    248             self._init_file()
    249 
--> 250             self.model = self._train_and_test()
    251 
    252             if self.show_plot:

~/opt/anaconda3/lib/python3.7/site-packages/skmultiflow/evaluation/evaluate_prequential.py in _train_and_test(self)
    373 
    374         if len(set(self.metrics).difference({constants.DATA_POINTS})) > 0:
--> 375             self.evaluation_summary()
    376         else:
    377             print('Done')

~/opt/anaconda3/lib/python3.7/site-packages/skmultiflow/evaluation/base_evaluator.py in evaluation_summary(self)
    615                 print('{} - Precision: {:.4f}'.format(
    616                     self.model_names[i],
--> 617                     self._data_buffer.get_data(metric_id=constants.PRECISION, data_id=constants.MEAN)[i]))
    618             if constants.RECALL in self.metrics:
    619                 print('{} - Recall: {:.4f}'.format(

TypeError: 'NoneType' object is not subscriptable

For what i can understand the issue is that what's returned by get_data is not a data structure when it should be but i can't understand what's causing it.
Thanks for the help.

**Comment by hitz9** [comment] 2020-05-16 17:01
Hi, can you help me?

https://github.com/scikit-multiflow/scikit-multiflow/issues/250

**Comment by smastelini** [comment] 2020-05-16 21:27
Hi @Askios, thanks for reporting that. Could you provide the complete MWE to reproduce your error?

Besides, do your data represent a binary classification problem? It is an important concern since the Half-Space Trees' are one-class anomaly detectors.

**Comment by Askios** [comment] 2020-05-16 21:56
I can provide you with the .csv file, as for the code is the same as the one i've pasted before.
About the data, i believe it to be a binary classification problem, as i only have two different labels for the target. With another software (Matlab) I generated the samples i needed for the 'normal'
 class and then swapped some of them outside of the training window with samples from the 'anomaly' class, which have a different target label.
Here's a [MEGA] (https://mega.nz/folder/kPZyDSTK#SZAFpmUVvvPN5xSVIJB78g) folder with both the .csv and the .ipynb i used.

**Comment by smastelini** [comment] 2020-05-17 15:11
Thank you for the data @Askios. I opened you notebook and was able to run your code after a minor modification. I'm using the development version of skmultiflow and didn't get any errors. However, what I found is generating an error is the parameter `n_features` you pass to `HalfSpaceTrees`. This algorithm actually does not have this parameter in its signature.

Please, let me know whether you are able to run the example properly with your data.

**Comment by Askios** [comment] 2020-05-17 15:22
Let me begin by thanking you for  the help although I'm not sure if i understand.
According to [the documentation](https://scikit-multiflow.github.io/scikit-multiflow/api/generated/skmultiflow.anomaly_detection.HalfSpaceTrees.html#skmultiflow.anomaly_detection.HalfSpaceTrees) n_features is a required parameter, literally the first one. Are you saying that I should try running the code without that?

**Comment by smastelini** [comment] 2020-05-17 15:44
My bad @Askios. I just checked and this parameter was removed from `HalfSpaceTrees` in a recent commit. Now the trees infer the number of features directly from the data. Anyhow, the mentioned problem does not seem to happen in the most recent version of the code.

**Comment by Askios** [comment] 2020-05-17 15:53
So i should just update the library?

**Comment by smastelini** [comment] 2020-05-17 15:56
I believe it is the easiest way to get your code running. Could you try the development version to check whether your problem persists?

**Comment by Askios** [comment] 2020-05-17 16:31
I updated the library to 0.5.0 and now the code is running.

**Comment by jacobmontiel** [comment] 2020-05-17 23:14
The `n_features` parameter was removed from the signature since it can be calculated from the data itself. This approach is in alignment with other estimators in `scikit-multiflow`.

**Comment by jacobmontiel** [comment] 2020-06-02 23:32
Closing as this question has been answered.

**Closed by jacobmontiel** 2020-06-02 23:32 UTC
Labels: question
