### ISSUE TITLE
[FEATURE] Adaptive Random Forest Regressor

### ISSUE THREAD

**Issue by jacobmontiel** [scikit-multiflow/scikit-multiflow#131] opened 2019-08-21 16:52 UTC
The `Adaptive Random Forest Regressor` is an adaptation of the `Adaptive Random Forest` classifier.

The implementation of this method is somewhat straightforward given that the original (classification) version and the base learner (Fastand Incremental Model Trees) are already implemented in `scikit-multiflow`. 

---
**Refrences**
Gomes, H.M., Bifet, A., Read, J., Barddal, J.P., Enembreck, F., Pfharinger, B., Holmes, G. and Abdessalem, T., 2017. Adaptive random forests for evolving data stream classification. Machine Learning, 106(9-10), pp.1469-1495. ([paper](https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2018-183.pdf))

**Comment by jacobmontiel** [comment] 2019-08-22 15:33
@AlbandeCrevoisier will be working on this. Pining @smastelini for support.

**Comment by hmgomes** [comment] 2019-08-22 21:38
There is an [ARF regressor](https://www.researchgate.net/publication/329397374_Adaptive_random_forests_for_data_stream_regression) implemented in MOA which can be used for reference (maybe comparisons?). The main difference is that it uses FIMT-DD as the base learner.

**Comment by jacobmontiel** [comment] 2019-09-03 23:09
@AlbandeCrevoisier Please create a PR when you have an initial version of the implementation so we can provide feedback.

**Comment by AlbandeCrevoisier** [comment] 2019-10-03 11:13
I — finally — opened a PR, looking for feedback :)

**Comment by smastelini** [comment] 2020-07-07 03:17
Closing since it was addressed in #145 and #237.

**Closed by smastelini** 2020-07-07 03:17 UTC
Labels: enhancement
