### ISSUE TITLE
[BUG] Hoeffding Based Tree Classifiers Dropping Class

### ISSUE THREAD

**Issue by jaygrth** [scikit-multiflow/scikit-multiflow#215] opened 2020-02-20 20:25 UTC
Hi,

I may have discovered a bug, a characteristic of all the Hoeffding based decision tree classifiers contained within multi-flow. I am training the classifier with three classes (5,10,15), with all class data being fed to the classifier at once (all class 10 samples, then all class 5 samples, etc.) The classifier will, of course, create rules once there is greater than one class and statistics deem split as useful. However, once I introduce the third class (15), the first class (10) disappears from the model.

![image](https://user-images.githubusercontent.com/20672353/74975157-37191780-53ec-11ea-9b0a-359bcfd2d347.png)

**Comment by smastelini** [comment] 2020-02-20 20:34
Hi @jaygrth, could you provide a MWE to reproduce the potential bug?

**Comment by jaygrth** [comment] 2020-02-20 20:53
Apologies!

**Describe the bug**
Class disappearing from model when trained in order of class

**To Reproduce**
Order samples in dataset by class. Incrementally train the classifier.
`    tree = VeryFastDecisionRulesClassifier(grace_period=10, expand_confidence=0.01,tie_threshold=0.5, expand_criterion='info_gain', max_rules=10, remove_poor_atts=False)
    for training_set in examples:
        print(len(training_set))
        x_train = training_set[:, 2:3]
        y_train = training_set[:, -1]
        start_time = time.time()
        tree.partial_fit(x_train, y_train)
        print(tree.get_model_description())
    print("--- Running time: %.6f seconds ---" % (time.time() - start_time))
`
**Expected behavior**
Model to keep statistics from class that it has not seen recently

**Comment by jacobmontiel** [comment] 2020-02-20 21:08
Hello @jaygrth 

The `VeryFastDecisionRulesClassifier` is based on the `HoeffdingTreeClassifier` but it is not the same.

From the [documentation](https://scikit-multiflow.github.io/scikit-multiflow/_autosummary/skmultiflow.rules.VFDR.html#skmultiflow.rules.VFDR), the behaviour you observe could be related to:
> To adapt with the concept every rule is equipped with drift detector to monitor it’s performance. When a change is detected then rule is removed and new one with be learned.


Original paper for reference:
> Petr Kosina and João Gama. 2015. Very fast decision rules for classification in data streams. Data Min. Knowl. Discov. 29, 1 (January 2015), 168-202. DOI=http://dx.doi.org/10.1007/s10618-013-0340-z

**Comment by jaygrth** [comment] 2020-02-20 21:40
As I understand it, drift detection would not impact a class that I am not training for. Also, I have specifically disabled drift detection for testing. I have confirmed this behavior with the HoeffdingTreeClassifier as well.

**Comment by jacobmontiel** [comment] 2020-02-21 01:58
I formated the MWE you shared. Please include the `examples`, otherwise, we can not reproduce this.

**Comment by jaygrth** [comment] 2020-02-21 15:59
I do apologize.

I have included the full dataset in my repo [https://github.com/jaygrth/data/blob/master/test_set.csv](url)

`df = pd.read_csv('test_set.csv', delimiter=',')
array = df.head(9000).values
    set1 = array[:1000, :]
    set2 = array[1000:2000, :]
    set3 = array[2000:3000, :]
    set4 = array[3000:4000, :]
    set5 = array[4000:5000, :]
    set6 = array[5000:6000, :]
    set7 = array[6000:7000, :]
    set8 = array[7000:8000, :]
    set9 = array[8000:9000, :]
examples = [set1, set2, set3, set4, set5, set6, set7, set8, set9]`

**Comment by jacobmontiel** [comment] 2020-02-28 07:50
Thanks for the data and the code @jaygrth, I was able to replicate this behavior. 

Here are my observations/comments.

What you are observing is caused by the transition of leaf nodes into split nodes. For the first two classes, the model only contains nodes that have observed two classes at most (5, 10). As a third class is introduced (15) some nodes start "seeing" samples that contain the new class. When enough samples have been observed the split is performed (Hoeffding bound). If a node has observed more than 2 classes, then the best 2 candidates are used for the binary split. This is where one class is "dropped".

This (expected) behaviour becomes more evident due to the setting of the experiment:
1. The samples are grouped by the class
2. The model description is printed after processing a new "set"
3. The order of classes and low dimensionality (only one feature for training (is this intentional?)

In reality, the split process is trigged close to where the new class is introduced. Regarding point 3, an easy counter-example is if you pass first `set9` then `set1`, `set8`. In this case, you will see that class 15 is retained by some nodes in the Hoeffding Tree.

Notice that the experiment setting is a very special case.

Here is another way to run your experiment, getting the description at fixed intervals so you can observe the split process:

```python
import pandas as pd
import numpy as np

from skmultiflow.rules import VeryFastDecisionRulesClassifier
from skmultiflow.trees import HoeffdingTreeClassifier
from skmultiflow.data import DataStream
import time

df = pd.read_csv('~/Downloads/data-master/test_set.csv', delimiter=',')
stream = DataStream(data=df.iloc[:, 2:3].values, y=df.iloc[:, -1].values)

vfdr = VeryFastDecisionRulesClassifier(grace_period=10, expand_confidence=0.01,
                                       tie_threshold=0.5, expand_criterion='info_gain',
                                       max_rules=10, remove_poor_atts=False)
ht = HoeffdingTreeClassifier()

tree = ht

samples_btwn_inspect = 100

for i in range(9000):
    X, y = stream.next_sample()
    tree.partial_fit(X, y)
    if i % samples_btwn_inspect == 0:
        print(i)
        print(tree.get_model_description())

```

**Comment by jacobmontiel** [comment] 2020-03-09 06:33
Closed due to inactivity.

**Closed by jacobmontiel** 2020-03-09 06:33 UTC
Labels: invalid, wontfix
