### ISSUE TITLE
[BUG] ARF predict_proba failing if first call to partial fit does not specify classes

### ISSUE THREAD

**Issue by luccaportes** [scikit-multiflow/scikit-multiflow#144] opened 2019-10-02 01:25 UTC
**Describe the bug**
If in the first call to partial_fit in ARF we do not specify the classes, ```predict_proba``` might fail. 

There are two possible errors that seem to have the same root.

1) It seems that predict_proba expects every array of votes to be of the same size, but that might not be true when the classes are not specified.

The error occurs in this line of predict_proba of ARF:

```y_proba_mean = y_proba_mean + (y_proba - y_proba_mean) / (i+1)```

And the error is:

```ValueError: operands could not be broadcast together with shapes (100,) (100,2)```

2) The second error also happens only when we do not specify the classes parameter in the first call to partial_fit. I did not completely understand what is happening, but the error is the following:

```ValueError: setting an array element with a sequence.```

And it happens when converting a variable to numpy array in the method ```check_array``` of the file ```utils/validation.py```.

This method is called by ```normalize``` in the file ```preprocessing/data.py```. And ```normalize```is called by ARF ```predict_proba```.

**To Reproduce**
This code should reproduce the first error:
```stream = AGRAWALGenerator()
stream.prepare_for_use()
model_orig = AdaptiveRandomForest()
x_train, y_train = stream.next_sample(100)
model_orig.partial_fit(x_train, y_train)
print(model_orig.predict_proba(x_train))
```

And the second one:
```
stream = AGRAWALGenerator()
stream.prepare_for_use()
model_orig = AdaptiveRandomForest()
x_train, y_train = stream.next_sample(1000)
model_orig.partial_fit(x_train, y_train)
print(model_orig.predict_proba(x_train[:100]))
```
Both can also be seen here: https://colab.research.google.com/drive/1iRT2r9h3emgvEBtdkntjgWPHcEbGgBn9

**Expected behavior**
I think one of the possible ways to correct that is to add in ARF partial_fit, the same verification that we have on OnlineBoosting:

```
if self.classes is None:
    if classes is None:
        raise ValueError("The first partial_fit call should pass all the classes.")
    else:
        self.classes = classes

if self.classes is not None and classes is not None:
    if set(self.classes) == set(classes):
        pass
    else:
        raise ValueError("The classes passed to the partial_fit function differ from those passed earlier.")
```
But I'm not sure how that would affect other people's code.

**Comment by jacobmontiel** [comment] 2019-10-04 08:22
Hi @luccaportes 

This is indeed a bug. The root cause is that the implementation of `predict_proba` is not handling correctly the use of mini-batches. There are other details missing as well. The following fix deals with most of them: 

```python
    def predict_proba(self, X):
        if self.ensemble is None:
            self.init_ensemble(X)

        y_proba = []
        y_proba_mean = None
        n_rows, _ = get_dimensions(X)

        for i in range(n_rows):
            for j in range(self.n_estimators):
                y_proba_current = self.ensemble[j].predict_proba(np.asarray([X[i]]))
                if y_proba_mean is None:
                    y_proba_mean = y_proba_current
                else:
                    y_proba_mean = y_proba_mean + (y_proba_current - y_proba_mean) / (j + 1)
            y_proba.append(normalize(y_proba_mean, norm='l1').flatten())

        return np.asarray(y_proba)
```

I will do further tests and try to get a more generic approach so `predict_proba` can be called from `predict`.

I made some small changes to your MWE for testing:

```python
from skmultiflow.data import AGRAWALGenerator
from skmultiflow.meta import AdaptiveRandomForest

stream = AGRAWALGenerator(random_state=1)
stream.prepare_for_use()
model_orig = AdaptiveRandomForest(random_state=1)

x_train, y_train = stream.next_sample(100)
model_orig.partial_fit(x_train, y_train)
x_test, y_test = stream.next_sample(10)
print(model_orig.predict_proba(x_test))

stream.restart()
model_orig.reset()

x_train, y_train = stream.next_sample(100)
model_orig.partial_fit(x_train, y_train)
x_test, y_test = stream.next_sample(100)
print(model_orig.predict_proba(x_test[:10]))
```

**Comment by jacobmontiel** [comment] 2019-10-06 23:09
Upon further investigation, I found that the bug is indeed triggered **only** when classes are not defined in the first call of `partial_fit`.

The root cause is the way we return probabilities from the base estimators. When no classes are defined, the resulting array is missing some values until all classes are observed. This caused the array to be a 1D array of lists with different lengths instead of a 2D array.

The current implementation of `predict_proba` in ARF expects a 2D array but receives pseudo-1D arrays, thus raising the errors. I am uploading a fix for this corner-case as well as a streamlined version of `predict` based on `predict_proba`.

**Closed** 2019-10-07 01:08 UTC
Labels: bug
