### ISSUE TITLE
HATT: AnyTimeLearningNodeNBAdaptive' object has no attribute 'get_attribute_observers'

### ISSUE THREAD

**Issue by yzhang0376** [scikit-multiflow/scikit-multiflow#120] opened 2019-06-21 02:00 UTC
**Describe the bug**
AnyTimeLearningNodeNBAdaptive' object has no attribute 'get_attribute_observers' , when put conditions for HATT(). 

**To Reproduce**
ExTree= HATT(grace_period= 50,split_confidence=0.0005, tie_threshold = 0.0001)
evaluator = EvaluatePrequential(pretrain_size = 100,n_wait=2, max_samples = 1000, metrics=['accuracy'], output_file=None)

evaluator.evaluate(stream=data, model=ExTree, model_names=['ExTree'])

If use ExTree= HATT() , only 200 samples are processed.

**Comment by jacobmontiel** [comment] 2019-06-24 22:11
Hello @yzhang0376, what kind of data (stream) are you using?

**Comment by yzhang0376** [comment] 2019-06-25 21:02
I loaded a .CSV file and transferred it to a streaming data by using prepare_for_use(). This data has total of 7500 observations and each of them with 150 features in training. All of the features are numerical. And this data works with HoeffidingTree algorithm with these settings.   Hope this answers your question.

**Comment by jacobmontiel** [comment] 2019-06-25 22:37
Hello @yzhang0376 

I have tested the above configuration on a stream from the `SEAGenerator` and could not replicate the error. 

```
Prequential Evaluation
Evaluating 1 target(s).
Pre-training on 100 sample(s).
Evaluating...
 #################### [100%] [25.34s]
Processed samples: 1000
Mean performance:
ExTree - Accuracy     : 0.7211

Process finished with exit code 0
```

What do you mean by:
> I loaded a .CSV file and transferred it to a streaming data by using prepare_for_use()

You can either load data from a file with `FileStream` or convert a data object with `DataStream`

**Comment by yzhang0376** [comment] 2019-06-26 01:27
Yes, I loaded data with FileStream().  Sorry I could not provide the screen shot now since there are some import problems after I updated to the 0.3.0 version, which I posted under User Group. Sorry for the troubles.

**Comment by yzhang0376** [comment] 2019-06-26 02:19
I found the problem. I still used the old version to import FileStream() after I updated to 0.3.0. Now fixed. Sorry about the misleading.

**Comment by jacobmontiel** [comment] 2019-06-28 15:10
No problem. Glad to report that this is not a bug. I am closing this issue.

**Closed by jacobmontiel** 2019-06-28 15:10 UTC
Labels: invalid
